services:
  database:
    image: postgres:18
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/
    environment:
      POSTGRES_DB: data
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/pgdata

  app:
    image: rustlang/rust:nightly
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/data
      JWT_SECRET_FILE: /run/secrets/jwt
      CARGO_TARGET_DIR: ../docker-target
      BIND_ADDRESS: "0.0.0.0:3000"
      SQLX_OFFLINE: true
      RUST_LOG: info
    working_dir: /app
    volumes:
      - .:/app:ro
      - cargo-cache:/usr/local/cargo/registry
      - build-output:/docker-target
      - secrets:/run/secrets
    command: >
      sh -c '
        if [ ! -f "$$JWT_SECRET_FILE" ]; then
          openssl rand -base64 32 > "$$JWT_SECRET_FILE"
        fi &&
        export JWT_SECRET=$$(cat "$$JWT_SECRET_FILE") &&
        cargo run --release
      '
    depends_on:
      - database

volumes:
  data:
  secrets:
  cargo-cache:
  build-output:
